version: "3.8"
services:

  web_app_tests:
    build:
      context: ./web_app
      dockerfile: docker/DockerfileTests
    env_file:
      - ./web_app/env/test.env
    volumes:
      - "./web_app:/web_app"
    depends_on:
      - postgres_tests

  postgres_tests:
    image: postgres:13
    env_file:
      - ./web_app/env/test.env

  web_app:
    build:
      context: ./web_app
      dockerfile: docker/Dockerfile
    ports:
      - "5057:5057"
    env_file:
      - ./web_app/env/local.env
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    env_file:
      - ./web_app/env/local.env
